/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS QMQ_OUT_HEADER (
    SOURCE TEXT NOT NULL,
    MESSAGE_ID TEXT NOT NULL,
    TARGET TEXT,
    MESSAGE_TYPE TEXT,
    EXPIRATION_TIME TEXT,
    REMARKS VARCHAR(40),
    MSG_STATUS CHAR(1),
    DATE_TIME_IN TEXT,
    DATE_TIME_PROC TEXT,
    RETRY_COUNT INTEGER,
    PRIMARY KEY (SOURCE, MESSAGE_ID)
);

DELETE FROM "QMQ_OUT_HEADER";
/*!40000 ALTER TABLE "QMQ_OUT_HEADER" DISABLE KEYS */;
INSERT INTO "QMQ_OUT_HEADER" ("SOURCE", "MESSAGE_ID", "TARGET", "MESSAGE_TYPE", "EXPIRATION_TIME", "REMARKS", "MSG_STATUS", "DATE_TIME_IN", "DATE_TIME_PROC", "RETRY_COUNT") VALUES
	('SOURCE', '20240315 184529', 'SYSTEM_TARGET', '3212', '1', '1', '1', '1', '1', 1),
	('1', '20240315 184632', '1', '3321', '1', '1', '1', '1', '1', 1),
	('SOURCE', '20240326 035737', 'SYSTEM_TARGET', '11112', '1', '1', '1', '1', '1', 1);
/*!40000 ALTER TABLE "QMQ_OUT_HEADER" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
