/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS QMQDb (
    Telegramm VARCHAR(50) NOT NULL,
    FieldSeq INTEGER NOT NULL,
    Feature VARCHAR(50) NOT NULL,
    Value TEXT,
    Factor VARCHAR(50),
    Type VARCHAR(20),
    Description TEXT,
    TableName VARCHAR(50),
    ColumnName VARCHAR(50),
    PRIMARY KEY (Telegramm, FieldSeq, Feature)
);

DELETE FROM "QMQDb";
/*!40000 ALTER TABLE "QMQDb" DISABLE KEYS */;
/*!40000 ALTER TABLE "QMQDb" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
